seo:
  site_name: Jessica Christie
  title: Every Little Thing
  description:
  keywords:
  social_image:
  author: Jessica Christie
  favicon_image:
social:
  instagram_username: '@ShadesOfJess'
  facebook_url: https://www.facebook.com/chiichobits/
  twitter_username: https://twitter.com/jc_chii
design:
  dark-text_color: '#555555'
  medium-text_color: '#5a5a5f'
  light-text_color: '#ffffff'
  featured-text_color: '#e7c7ef'
  dark_color: '#555555'
  medium_color: '#ede8e4'
  light_color: '#ffd5ef'
  v-light_color: '#ddfdfe'
  featured_color: '#e7c7ef'
  accent_color: '#e8e8ff'