seo:
  site_name: Jessica Christie
  title: Every Little Thing
  description:
  keywords:
  social_image: /icons/apple-touch-icon.png
  author: Jessica Christie
  favicon_image: /icons/apple-touch-icon.png
social:
  instagram_username: '@ShadesOfJess'
  facebook_url: https://www.facebook.com/chiichobits/
  twitter_username: https://twitter.com/jc_chii
design:
  dark-text_color: '#555555'
  medium-text_color: '#5a5a5f'
  light-text_color: '#ffffff'
  featured-text_color: '#e7c7ef'
  dark_color: '#555555'
  medium_color: '#ffb8d1'
  light_color: '#ffd5ef'
  v-light_color: '#ddfdfe'
  featured_color: '#e7c7ef'
  accent_color: '#e8e8ff'
  cone_color: '#ffcb85'
  choco_color: '#6b3e26'
  berry_color: '#ffc5d9'
  mint_color: '#c2f2d0'
  vanilla_color: '#fdf5c9'